### ISSUE TITLE
안녕하세요 새별님 

### ISSUE THREAD

**Issue by oh930428** [NewStarYim/mystargram#1]
안녕하세요 새별님 코드 잘봤습니다  확실히 경력이 있으셔서 그런지 정말 깔끔하네요 ㅎㅎ
확인 해보니 emotion을 쓰셨네요??  styled-components를 써보셔서 emotion을 쓰시는건가요 ??? 
그 이유가 궁금합니다

**Comment by NewStarYim** [comment]
안녕하세요, 스타일드 컴포넌트는 기존에 한번 사용해봐서, 비슷한 emotion이 있길래 한번 사용해봤습니다.  단지 스타일드 컴포넌트의 경우 ssr에서 별도의 설정이 추가로 필요해서 emotion을 사용하게 됐습니다! 지금 프로젝트에서는 ssr을 안쓸수도 있지만, 제가 앞으로 진행하는 프로젝트에서는 ssr이 들어갈 것 같은데, emotion은 따로 설정을 할 필요가 없어서요!

**Comment by oh930428** [comment]
답변 감사합니다 새별님
